- loganalyzer.py
This PR adds and amends the following:
- Fixes version detection on Linux
- Logs from Linux versions of OBS were showing as "old version" and the check was returning "OBS" on those builds. This fix checks that "OBS" is not being detected on the second string either, and uses the correct string if it is.
- Downgrades the "Beta version" alert from Warning to Info
- This is mostly for future-proofing at this point, since betas aren't active, but they're not really worth being a "warning" imo.
- Add release candidate check.
- Add an info alert for RC builds of OBS Studio 23.0
> Version Check Updates

- loganalyzer.py
This PR includes the following:
- Update variable CURRENT_VERSION to 23.0.0.
- Changes the "Wrong Preset" warning.
- "Wrong Preset" isn't entirely accurate, and it's also not warning worthy. The analyzer now reports "non-default x264 preset" with an info level.
> Update current version + x264 preset change

- loganalyzer.py
...because "Display Capture" is the terminology users see in the UI and
most other places this feature is referenced.
> rename 'Monitor Capture' -> 'Display Capture' in output

- loganalyzer.py
Check windows version, warn on out of support versions
Also, remove extra comma from end of error/warning summary
Also, allow "--file xxxx" for testing from local files. I could make this a separate PR if desired, was mostly trying to avoid having too many interdependent changes in flight at once. This also requires the severity-by-name PR (#22 
Tested with a dozen or so random logs, and appears to do the right thing, additional testing or comments gladly accepted.
> Windows version checks

- loganalyzer.py
Minor QoL change, makes it possible to see a user's windows version (translated from build number) without having to click through to the log analysis.
> put windows version in title of win version check entry

- loganalyzer.py
should either do this, or come up with thresholds and actually call this (probably ok to just remove, given that systems without enough memory probably wont' have enough anything else either)
> cleanup: remove unused 'checkMemory' function

- loganalyzer.py
This is a win10 (sub)version-specific check, just skip it if it's a win10 version we don't recognize, rather than crashing out and/or trying to guess what's appropriate. We also updated the 'unknown Windows 10 version' text to note that windows-version-specific checks won't be performed.
> fix game mode check crashing on unknown win10 versions

- loganalyzer.py
Add build number/version for win 10/2004. Also update the windows version checker to deal with not knowing the ship/EOL date of a windows 10 release, since those haven't happened/been announced for this release (AFAIK)
> add win10 build number for 1H2020 release (19041/2004)

- simplehttp.py
Modify genBotReponse() to support outputting detailed information entries instead of only titles
Moving the analyzer within the website CMS framework requires an API endpoint with all log data
Tested with new **detailed** parameter set to random strings, true, false and not set at all
New feature (non-breaking change which adds functionality)
> Support detailed information in JSON response

- loganalyzer.py
In 24.0.3 (and earlier), the windows build information provided in the OBS log is the same for Windows 10 release 1903, and Windows 10 release 1909. This change has the log analyzer report the windows version as "1903/1909" to avoid stating potentially incorrect information as though it were fact, and hopefully removing a modicum of confusion in the process.
> note win10 1903/1909 uncertainty in OBS <= 24.0.3

- loganalyzer.py
Per https://support.microsoft.com/en-us/help/4557164/lifecycle-changes-to-end-of-support-and-servicing-dates
We only track non-enterprise support dates, so only win10/1809 needs
to be updated.
> update with new COVID-19 inspired win10 EoS dates

- loganalyzer.py
Because we don't have a mutex on log output, lines can sometimes get
mixed together. If this happened for an "adding XX milliseconds of audio
buffering" line, the analyzer would crash out because the millisecond count
wasn't in the string position it should have been.
We now parse with a regex, and give ourselves a little bit of framework for
doing fancier things in the future.
> don't crash out on misformated audio buffering lines

- loganalyzer.py
HAGS is currently known to cause severe performance and capture issues with some users and must be disabled
Adds critical warning when HAGS is turned on
Comes with a suitable Wiki page: https://github.com/obsproject/obs-studio/wiki/How-To-Disable-Windows-10-Hardware-GPU-Scheduler
Several performance issues when this is on. Needs probably a few more Windows or driver updates before it's negative impact is gone. There is currently no software or game that makes use of this feature in any way.
Used a log with and without HAGS
- HAGS On - https://obsproject.com/logs/HSDADanYZu0S_xKI 
- HAGS Off - https://obsproject.com/logs/jyRFYM7zL3jPUmmY 
- No HAGS entry (random log) - https://obsproject.com/logs/pul7ZWuk6h0D9H6D
> Add critical warning for HAGS

- checks/network.py
- loganalyzer.py
This adds checks for dynamic bitrate and non x264 encoders. Checks for dynamic bitrate, and if present checks for non-x264 encoders. Depending on the out the encoders found, an INFO or WARNING will be returned.
Users dont always understand the implications of enabling dynamic bitrate, especially the challenges that might occur when non-x264 encoders are in use. This not only inform users of of the fact and explains it to them, and also adds helpful information for support volunteers.
Seeing as most hardware encoders are prone to crashing or issues with dynamic bitrate in certain circumstances, a warning when using dynamic bitrate + non-x264 encoders will hopefully lead users to be more informed about the issues and consider other options. Should hopefully also lessen the load slightly on …
> Add dynamic bitrate checks

- checks/network.py
- loganalyzer.py
Added a simple check that searches for `second delay active` in log lines. If found, create an Info message.
There are several users that seem to accidentally manage to trigger the delay on their stream without being aware of the consequence. This is just meant as a heads up/reminder that it is enabled, and explains to them what it is, and how to potentially disable it.
It also makes it easier for support people to notice the delay.
Using the simple web server, I ran it thru the following logs:
Simple mode:
Delay off: <https://obsproject.com/logs/5ByyTBd-fgyDodaB>
Delay on: <https://obsproject.com/logs/mwvDT0XwbmKaJ3P9>
Advanced mode:
Delay off: <https://obsproject.com/logs/JY_tQ9E5wwmLVXFC>
Delay on: <https://obsproject.com/logs/e7d-mfCm3Ash3HYg>
It produces the expected output, and does …
> Add check for Stream Delay

- checks/windows.py
Add Windows 11 Insider detection
The first version of Windows 11 Insider Preview is out with the build number 22000.     
Any Windows builds with build number greater than 22000 should be Windows 11.  
But Windows 11 is not released to the public yet, so we can safely assume all Windows 11 build will be Insider builds. 
> Add Windows 11 Insider detection

- checks/core.py
Adds the OBS version number to the "Old Version" check
Also minorly modifies the existing string adding the "Check for updates" menu in OBS as a way to update
There is similar functionality for the OS check, I kinda think it would be a nice addition
Grabbed an old log from `#windows-support`, correctly shows the version number.
Example:
> Show OBS version number for Old Versions

- checks/encoding.py
When starting multiple encoding sessions with NVENC (or other hardware
encoder) and receiving encoder overload, it was still reported as
"Encoder Overload", and not specifically as "GPU Encoder Overload".
Reason being: We count lines for each encoder. We then add those up and
check if the count is greater then 1. This check is intended for
mixed-encoder logs (i.e. x264 + any hardware encoder). However as 2
encoding sessions of any encoder is already greater then 1, we get
caught on the first case and never get to the further cases.
Essentially we only want to check if both types of encoders were used at least once.
It was mentioned and asked on Discord why a double NVENC log showed up as "Encoder Overload", and not "GPU Encoder Overload" specifically. Looking at the code it made sense to …
> Fix Encoder overload detection on multiple encodes

- checks/core.py
This commit changes how the version detection works by removing everything in the version lines not relevant to version detection.
The current 3 cases essentially cover whether:
* the log was uploaded in-app, resulting in an additional logs line like:
`OBS 27.1.0~rc2 (linux) log file uploaded at 2021-09-14, 10:22:24`
* the log was uploaded otherwise, resulting in the logged version being detected:
`01:46:09.110: OBS 27.0.1 (64-bit, windows)`
* there are weird edge-cases with malformed/different timestamps (but obviously not all of them)
Instead of working our way around the various ways timestamps could be presented, this instead removes everything before "OBS" (which should be only the timestamp), and we can focus purely on the version itself, which is then always `split()[1]` (and if …
> Simplify version detection

- checks/network.py
This removes the warning for dynamic bitrate when using hardware encoders.
Will leave this as a draft (and a reminder) until the next OBS release, and we've gotten confirmation of the hardware encoders now work in a stable manner on more machines.
Now that https://github.com/obsproject/obs-studio/pull/5169 has been merged, and assuming it works well, there is no longer a reason to put up warnings for its usage with hardware encoders.
Running the simplehttp server on my machine, and testing the changes with the following:
Dynamic Bitrate:
nvenc simple: <https://obsproject.com/logs/y74C5azqJ41JGJf_>
nvenc advanced: https://obsproject.com/logs/zrjWLYYT7AfcBN9I
x264 advanced: https://obsproject.com/logs/xwFM8BJxgYmokzpU
x264 simple: https://obsproject.com/logs/S88uiveJ9RkGE2rL
Traditional …
> Remove warning for hw encoders in dynamic bitrate

- checks/core.py
Changes the wording for the insufficient hardware note to include all hardware encoders, not just quicksync.
This change was suggested by Bavario#4681 because quicksync isn't always the best option to use for encoding in this case, you can see the full conversation about it [here](https://discord.com/channels/348973006581923840/376042662580715521/902177649588338778).
Did not feel it was necessary to test, a small change to a string.
> Update wording for insufficient hardware check

- checks/utils/windowsversions.py
- checks/windows.py
Add Windows 11 and 10 21H2 EoS date.
Windows 11 is released on October 5th, 2021.
> Windows 10/11 21H2 End of Service Date

- checks/encoding.py
Frame rate was wrongly taken from `keyint` reported by the NVENC streaming session. The frame rate is corrected to be taken from the global video settings.
According to a discussion on Discord, the stream bitrate is too high but it is reported too low.
https://discord.com/channels/348973006581923840/374636015396192257/912208926836129862
Tested with the same log file and confirmed the `Low Stream Bitrate` is no more reported.
https://obsproject.com/logs/MljccFMDFkUc0w5t
- Breaking change (fix or feature that would cause existing functionality to change)
Assuming `keyint` is usually set to 2 seconds, this change may increase amount of ` Low Stream Bitrate`.
> Fix NVENC low stream bitrate threshold

- checks/graphics.py
Modifies the color format check to accept P010 as valid. Added P010 to the user facing text.
People using P010 to stream is now a valid usecase for HDR (youtube HLS livestreaming for instance).
It does not incur "incur increased CPU usage due to color format conversion" as the other formats might.
Tested with the following logs, and made sure NV12 and P010 clears the check.
P010:
https://obsproject.com/logs/vPvBonXWjLqVG0xb
i420:
https://obsproject.com/logs/BaS5cg2eV1V27NfL
nv12:
https://obsproject.com/logs/kLjH6O7qIoGSUPY2
> Graphics: Add P010 as valid color format

- setup.cfg
Adds excluded directories from being processed pep8.
* venv and .venv
* env and ENV
* __pycache__
Mostly aligned with what is in .gitignore.
Don't want it to check those dirs. Easier to run when you don't have to specify individual files or folders. Prior to this change, if you run pycodestyle.exe --config=setup.cfg . on win , it would check venv, and of course spew out hundreds of issues from deps/pips.
On win10 22H2. Confirmed the excluded directories don't get checked (no errors from the deps/pips).
> Exclude venv and pycache from pycodestyle

- checks/graphics.py
Updates the wording for color range.
In OBS, we no longer call it Partial, its now Limited.
Don't want users to be confused that they can't find the option we tell them to set.
https://obsproject.com/logs/ZUFRyCvpM9NYMhIC
On win, with this log.
> Graphics: Update color range wording

- checks/windows.py
Adjust the game mode wording to just say "Windows" instead of "Windows 10".
Users in support are sometimes confused that they are using Windows 11 but the bot message says Windows 10 Game Mode.
Ran the log analyzer code locally with my changes, tested logs with game mode on to confirm it now displays as "Windows Game Mode"
https://obsproject.com/logs/RoBHVxIqDBZeJy3Y
> Remove 10 from "Windows 10 Game Mode"

- checks/plugins.py
Adds `decklink`, `aja`, and `aja-output-ui` to the list of first-party plugins.
Saw a log in macOS-support that complained about a third-party plugin `decklink`.
Decklink of course is first-party.
macOS 13.2.1
Tested locally that https://obsproject.com/logs/DUMelPUidIatJdmz no longer throws a warning about third-party plugins.
> checks: Add aja and missing decklink plugins to plugin list

- checks/encoding.py
This changes the current MP4/MOV check to only flag if the fragmented MP4 muxer settings are not being used.
OBS 29.1.0 added the use of fragmented MP4/MOV which does not present the same dangers as the previous implementation.
Tested a log with an MP4 recording on 29.02 and it still flagged where an MP4 recording on 29.1.0 using the fragmented MP4 muxer settings did not.
> Add fragmented MP4 exclusion to MP4/MOV check

- checks/core.py
When checking possible lines for the OBS version, skip the uploaded log header as its version may not match the actual version of OBS that was running for the logged session.
Want uploaded logs to have the version correctly checked.
Tested locally.
> Fix getOBSVersionLine for uploaded logs

- checks/core.py
Check for the Lenovo Vantage log message and adjust the version line accordingly.
Noticed this log crashes the analyzer with an index out of range, this was the suggested fix by Matt and Ryan.
https://obsproject.com/logs/P0U7doFsxkOqOTLL
Tested with the above log, no longer crashes.
> Fix getOBSVersionLine when Lenovo Vantage is installed

- checks/plugins.py
This fixes a parsing issue that was resulting in a plugin name being incorrectly displayed on the analyzer results page.
I saw this log in the support discord: https://obsproject.com/logs/XmQtglRbVpBW3YfN
It parses obs_shaderfilter_plus_windows_x64 (1).dll as (1) currently but parses correctly after these changes.
This also fixes pastebin links which were adding \r to the string being read by the plugin formatter:
https://pastebin.com/bUGt5L46
Tested with the above logs to confirm the fix and then various other logs to check for unexpected issues. 
> Fix third-party plugins parsing

- checks/plugins.py
This updates the plugins list to exclude from the third-party plugins detection. With this change, obs-webrtc is now included in the common plugins, obs-qsv11 has been added to the Linux plugins, and coreaudio-encoder has been moved from the common plugins to the Windows and Mac plugins.
obs-webrtc is now being shipped with with OBS on all platforms, obs-qsv11 has been added to Linux builds, and it was pointed out the coreaudio-encoder is not available on Linux.
Tested a log with obs-webrtc installed, it no longer shows as a third party plugin: https://obsproject.com/logs/TCpUxI4EUKztOZuj
Didn't have a Linux log to test but I can't think of any potential issues here.
> plugins: Update plugins list for obs-webrtc, obs-qsv11, and coreaudio-encoder

- checks/utils/windowsversions.py
Change the release to 2009 as it needs to be an int.
#138  broke the analyzer when it needed to do the game mode check as that depends on the release being an int.
Tested with a log that was broken
https://obsproject.com/logs/cabUIFOmJ9itg53x
> windowsversions: Change 23H2 release to 2009

- checks/core.py
List the modules not loaded as a result of Safe Mode being enabled.
This gives a user more visibility to what Safe Mode is preventing from loading.
Tested with this log: https://obsproject.com/logs/AmHOz18shktiz0iV
> core: List modules not loaded in Safe Mode check

- checks/core.py
- loganalyzer.py
This adds detection and reporting of the Snap Package. Snaps are built on Ubuntu Core and the Logfiles report it as such. Therefore we have a fairly save way of detecting them.
Theoretically this could report a false positive for users that are actually running OBS on Ubuntu Core, however since Ubuntu Core is ["optimised for IoT and Edge"](https://ubuntu.com/core), it is arguably unfit for OBS anyway.
I was unsure which Log-Level to use, the Info-Text is hopefully written as neutral as can be. Obviously open to suggestions for improvement.
In the Linux Support channel we regularly receive reports from users experiencing crashes or other issues who turn out to be using the Snap Package. Snap is the default install method on Ubuntu now and therefore users will often install the Snap Package …
> core: Add Detection of unofficial Snap Package

- checks/macos.py
- loganalyzer.py
Check for any permissions that are not granted on macOS and list them with a warning flag.
Suggested on the community Discord server.
Tested logs with all permissions granted and with some missing.
https://obsproject.com/logs/cJpEIqQu07UoAdX1
https://obsproject.com/logs/rOK9qz0wdlw0KOQ3
> checks: Check for permissions not granted on macOS

- checks/utils/fetchers.py
Modify the regular expression for the matchDiscord function to include the query parameters which the Discord API expects.
Saw logs failing to parse with a "NO LOG" error in the Discord server.
Testing with this log URL: https://cdn.discordapp.com/attachments/355827402561159178/1217544190716805302/2024-03-12_22-41-48.txt?ex=66046963&is=65f1f463&hm=1044577dc373af1519f996eb78e3a96fe94ccd6c4e19dd8437f8ce953eec7222&
Previously only `374636015396192257/1209173862395420702/2024-02-17_18-25-28.txt` was being matched which resulted in a 403 response when using the Discord API. Now the full query is matched and passed through to the API.
Before:
After:
> utils: Include query parameters in matchDiscord function

- checks/windows.py
When analyzing a log for a custom OBS version, the version string comparison would result in checkGPU thinking that the version in the log was less than '23.2.1'. This resulted in using the pre-23.2.1 adapter indexes, which started at 1 instead of 0. This, in turn, resulted in the analyzer thinking that there was only one GPU in the system. If OBS is running on the dGPU, Adapter 1 would often be the iGPU. If this iGPU was an Intel iGPU, the analyzer would emit an "Integrated GPU" warning.
Instead of basing the adapter indices on the OBS version, which may have required processing the OBS version string or adding new version string processing functions, we can simply try adapter indexes 0-2 and treat index 0 as if it were possible that it doesn't exist with a try-except on each call as we …
> windows: Fix GPU check for custom OBS versions

- checks/windows.py
For OBS Studio 29.1.0-beta1, 64-bit OBS did not output "64-bit" in its logs. While this was fixed for OBS Studio 29.1.0-beta2, the check as it is currently would probably also catch a hypothetical native WoA (Windows-on-ARM) build. Additionally, the change in this commit is what the live log analyzer has been running for about a year. Checking for the presence of the undesired indicator ("32-bit" or "32bit") seems more correct than checking for the absence of the desired indicator ("64-bit" or "64bit").
Want the checks to be correct. Want the live log analyzer to be in sync with this repo.
Tested a log from OBS Studio 29.1.0-beta1 locally to make sure this didn't regress.
- Code cleanup (non-breaking change which makes code smaller or …
> windows: Fix check32bitOn64bit

- checks/network.py
- loganalyzer.py
Add checks for Network Optimizations and TCP Pacing.
Detect whether the user has set these options without having to dig through the log manually. Emit an INFO message since this is typically not critical.
Tested locally on Windows 11.
> network: Add checks for advanced network options

- .github/workflows/main.yml
Update marian-code/python-lint-annotate to v4.
Update the last remaining action to a modern version based on node20. The action's v2 somewhat avoided this, but was generally outdated, while its v3 still used the outdated node16.
Tested on my fork. Verified that v3 emitted node16 warnings while v4 did not.
https://github.com/RytoEX/loganalyzer/actions/runs/8652789123
https://github.com/RytoEX/loganalyzer/actions/runs/8652846033
- Code cleanup (non-breaking change which makes code smaller or more readable)
> Update marian-code/python-lint-annotate to v4

- checks/core.py
This changes the `getOBSVersionLine` function to be less reliant on the ordering of the lines in the OBS log.
Due to the Lenovo vantage reporting being printed to log before the "hide from screen capture" one, the log analyzer reported an unparseable obs version for any log which had detected lenovo vantage.
An example log can be found [here](https://obsproject.com/logs/p6E9BB5QwEklBJKX).
This was tested manually by feeding the lines to the function and checking it returns the correct one.
If only"wrong" lines are found it will return the last one so as to return something.
> core: Fix OBS version reported as unparseable

- checks/core.py
`getOBSVersionLine()` was finding:
`<timestamp>:  - com.obsproject.Studio.Plugin.OBSVkCapture` for users with this extension, therefore `getOBSVersionString()` ran into an IndexError on splitting the (invalid) `versionString`.
Therefore filtering out any lines that contain the Flatpak identifier.
Noticed Discord Bot noping out on some logs, fixed it.
Before:
```
$ ./loganalyzer.py -u https://obsproject.com/logs/PgEsS0ZxLEhOqgfO
Traceback (most recent call last):
File "/home/tarulia/Development/obs-loganalyser/./loganalyzer.py", line 221, in <module>
main()
File "/home/tarulia/Development/obs-loganalyser/./loganalyzer.py", line 215, in main
msgs = doAnalysis(url=flags.url, filename=flags.file)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> core: Fix version detection with Flatpak VKCapture

- checks/core.py
Adds OBSBasic to the wrongLines array so it will be excluded from the version check.
Fixed OBS 30.2+ log analysis, will fail to parse otherwise.
Tested with a 30.2 beta log https://obsproject.com/logs/rOvTTkjkAXfnWIE3
> core: Add OBSBasic to version line exclusions

- checks/audio.py
- checks/encoding.py
- checks/graphics.py
- checks/macos.py
- checks/network.py
- checks/windows.py
This guards all string to float/int conversions in the analyzer inside try-except clauses, to ensure that it fails gracefully if the string fed to it is not a valid float/int.
Due to the ever-changing nature of obs logging, especially with localisation and third-party plugins, it cannot be guaranteed and future-proofed that a given search or regexp will always fetch the bit of the log that it is supposed to.
If, as a result of this, the analyzer calls `int()` or `float()` on a string that is not a valid number, it will cause an exception and abort the whole analysis.
For example, as a result of the french localisation adding an unexpected set of parentheses in the name of the replay buffer, [this](https://obsproject.com/logs/ISyC5cm0qKjOTv8Y) log fails the whole analysis when trying to …
> checks: Guard float/int conversions

- checks/core.py
Remove the wrongLines list in favor of using regex to target the specific version line. My regex is not great so there is a chance I am over simplifying it but this is what I have gotten to work through trial and error. I am happy to change the regex if a better option is presented but this covers all of the different cases in the logs that I was able to find.
This will allow for less maintenance in the future to prevent the analyzer from crashing if a new line is logged before the OBS version is that includes "OBS". 
Tested the following logs, all with various versions from different versions dating back to 0.0.1 on Linux.
https://obsproject.com/logs/g9mDoXFJfiQvUsyH
https://obsproject.com/logs/Oj9J1vvGlDykmesH
https://obsproject.com/logs/ubenZ416XhbHkMO8 …
> core: Use regex to parse OBS version

- checks/audio.py
This removes the checkAudioBuffering function from the log analyzer.
In all of my time in support, apart from the application audio capture buffering issues which have been solved, this has rarely contributed to the interaction and almost always detracts from it. Nearly every instance of this error relates to sources that are not actually using audio or sources that hit max audio buffering, reset, and then had no issues all without the user noticing. Most see this critical error and assume it is the cause of their unrelated issue. This usually leads to a conversation explaining that if a user is not actually experiencing any audio issues you would expect (cutting out or audio going totally silent), this can simply be ignored anyways.
Still works fine, nothing else depends on this …
> audio: Change checkAudioBuffering to LEVEL_INFO 

- checks/windows.py
Prevent the "Wrong GPU" message when both adapters are the same.
Saw this log was triggering the error message: 
https://obsproject.com/logs/BaZPLgfCwGAtNWc9
Tested the log above to confirm it is resolved along with a few logs where the message should still show up like this one:
https://obsproject.com/logs/StrpkEaUZ2OzKHqQ
> windows: Ignore duplicate adapter names

- checks/network.py
- loganalyzer.py
This adds a warning if the maximum recommended video bitrate from the selected service has been exceeded.
Requires https://github.com/obsproject/obs-studio/pull/10917 to be merged first.
Added logging to OBS to display max bitrate when the user elects to ignore the service recommendations, this brings that to the analyzer as well.
Tested with this log https://obsproject.com/logs/ZuadI85OgoP0Yjjj
> network: Check max recommended bitrate from service
