obsproject/loganalyzer

loganalyzer.py

"For better rerformance as well as game capture ..."

Fix a typo in warning messages

---

loganalyzer.py

This adds a critical error when the Microsoft Basic Render Driver is detected

Add detection for Microsoft Basic Render Driver

---

loganalyzer.py

Minor typo fixes for the analyzer. 
I also removed a line of debug code for the bandwidth estimate that found its way into the repo. Very minor changes, altogether.

Typo Fixes

---

loganalyzer.py

Website now forces HTTPS and the location slightly changed

Fix Killer NIC driver download link

---

loganalyzer.py

Fix link to OBS wiki Game Mode page

---

loganalyzer.py

Based on an interaction in #help-and-support

Explain where to change video settings

---

loganalyzer.py

...also minor reformatting courtesy of autopep8

Use named constants for severity levels instead of bare ints

---

loganalyzer.py
simplehttp.py

Missed the way the web frontend worked during testing. Oops.

fix broken bot-supporting api calls

---

loganalyzer.py

Specifically:
- Game Bar no longer matters one way or the other
- Game DVR (non-background) no longer matters one way or the other
- Game DVR Background Recording always matters and gets its own warning
- Game Mode gets a warning if enabled with Win10 1803 or older
- Game Mode gets an info if disabled with Win10 1809 or newer
Tested with an assortment of logfiles collected from Discord over the last few weeks.

rework Windows "gaming features" warnings

---

loganalyzer.py

Identify beta and release candidate builds by a specific -suffix, rather
than looking for certain version-specific strings.
Display the specific version string in the output for these builds.
Don't flag a weird build string as "old version" -- flag as unparseable instead
Note for the user that beta or release candidate builds may have problems,
and that they should upgrade to a releae build as soon as one is available.

Better handling of beta/release candidate builds

---

loganalyzer.py

If render lag is 3% or greater, make the 'not admin' message into a warning.
Also change the thresholds on render lag messages slightly, based on my
fairly subjective observations of what levels people consider to be a
problem, and what levels they consider to be a huge problem. I think the
'warning' threshold might still be too high, but we'll see.
Old thresholds:
Info: pct < 5%
Warning: 5% <= pct < 15%
Critical: pct >= 15%
New thresholds:
Info: pct < 3%
Warning: 3% <= pct < 10%
Critical: pct >= 10%

Raise severity of 'not admin' message if render lag present

---

loganalyzer.py

Also fixes parsing of the Windows version linem, which changed in OBS v25
For the purposes of this check, fractional framerates are rounded so that e.g. 59.94 == 60,
which is generally not a problem for people.

Flag mismatched monitor refresh rates on Windows before Win 10/2004

---

loganalyzer.py

Add a missing period to the Capture Interference message
Someone PMed me about it on the forums, and they were technically grammatically correct.
Visual inspection
- Documentation (a change to documentation pages)

Add missing period

---

checks/encoding.py

adds a section to the encoder overload message about how the GPU can cause encoding issues as well if you are using the GPU to encode. 
fixes an issue where when the analyzer sees encoder overload in the log, it assumes that the CPU is encoding which can lead to false information and confusion for people using their GPU to encode. https://ideas.obsproject.com/posts/1429/
Running the simplehttp server on my machine, and testing the changes with https://obsproject.com/logs/-FsI6X8YCDM5Y7p2 and making sure it outputted the correct result. 

Adds that GPU can cause encoder overload

---

formatcode.sh

Adds a script to auto-format the code.
File is named the same as in obs-studio because it's meant to do the same.
Instead of having to do the formatting yourself, this should fix most of the formatting issues.
macOS 11.2.3, zsh 5.8
Fixed all issues I introduced myself. The description of autopep8 makes it appear as if it doesn't necessarily completely comply with pycodestyle which is why I added the check afterwards, but for me that never even had thrown anything (except when I manually forced it to do so, to check that the check works).

Add auto-format script

---

checks/encoding.py

Searches for what encoder is being used if there is encoding overload and spits out the correct guide for them to follow to fix it. If it detects multiple encoders it will spit out the old message, but if it only detects one encoder in the log, it will spit out the correct guide for that encoder. it also specifies in the name of the message if it is GPU or CPU Encoding Overload and if multiple encoders are detected it just calls it Encoding Overload. This part was to make it easier to know which it is from the bot message in discord. this is a fix of #72 which the branch had been screwed up and i felt it best to start on a new branch
This will make it easier for people to troubleshoot encoding overload based on what encoder they are using. This was the best building block I could think of …

Add search for the encoder

---

checks/utils/macosversions.py

macOS Monterey has been announced at the WWDC as macOS 12.
This also makes it clear that Apple will from now on bump major versions
instead of minor ones for new releases of macOS (hence the comment is
removed).
Enables the macversions check for macOS Monterey, which so far just got ignored.
Test-Environment: macOS 12.0 (21A5248p), Intel
Tested with logs from both 11.4 (to confirm this doesn't break anything) and 12 to confirm everything works as intended. 
(Sample log from macOS 12: https://obsproject.com/logs/iKfmr1urx8Lju-Q3)

Add macOS 12.0 Monterey to macversions

---

checks/utils/windowsversions.py

Update EoS dates for Windows 10 from Microsoft
Windows 10 is dead. Long live the Windows 11.  
Farewell Start tiles, it was a good run while it's still there.  
ref: https://docs.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro

Update EoS dates for Windows 10 from Microsoft

---

checks/encoding.py

This updates the logging message that the analyzer gives to make it make more sense when reading it.
I noticed that the message the analyzer was giving didn't make tons of sense so I decided to quickly make an edit to it.
No testing needed, string change

Update the GPU encoding overload message

---

checks/core.py

The newly logged "Hide OBS windows from screen capture" was causing the version check to break on local files. This commit accounts for that newly added log line.
The broken version check was causing confusion while providing user support.
I've tested this locally against my own OBS Studio 27.2.1 log files, and I've manually checked the output of the version check functions.

Handle new log lines in OBS 27.2.1

---

checks/graphics.py

Fix a typo in string from aspect ration to aspect ratio
Pointed out on discord [here](https://discord.com/channels/348973006581923840/374636084883095554/960202296044695552) and we don’t want typos
No testing needed, string change 

Fix string typo 

---

checks/sources.py
loganalyzer.py

This checks if needed browser components are properly loaded in obs.
Suggested on the obs discord https://discord.com/channels/348973006581923840/376042662580715521/959219016604454912
tested locally and confirmed it worked when it should and that it didnt work when it shouldn't. 

Check if Browser Components are loaded

---

checks/utils/macosversions.py

Update macOS versions
Update macOS 12 date. Add macOS 13.
Keep things updated.
Hasn't.

Update macOS versions

---

checks/macos.py

Find either "Mac OS X" or "macOS" for the Mac OS Name
Allow the analyzer to handle either "Mac OS X" or "macOS" to cover a potential logging change.
We may change the logging to list "OS Name: macOS" instead of "OS Name: Mac OS X", but we want to handle either case.
Tested locally with log files that were manually adjusted to contain "OS Name: macOS".

Find either "Mac OS X" or "macOS" for the Mac OS Name

---

checks/graphics.py
loganalyzer.py

Warn users why they lost window capture functionality.
Is there a way to test this? I just pulled the snippets from logs and based on the wayland checks.

Add NVIDIA 390 on EGL warning for 28.0.0+

---

checks/utils/macosversions.py

macOS 13 officially released on October 24, 2022. Update the release date and remove the comment about it being in beta.
Don't want confusing/incorrect data or comments in the code.
It's a non-functional change, so I haven't tested it.
- Code cleanup (non-breaking change which makes code smaller or more readable)

Update macOS 13 release date

---

checks/windows.py

Adjust the integrated GPU check to ignore a GPU that has "Arc" in the name.
Fixes #103 
Noticed the analyzer was incorrectly reporting this.
Ran the log analyzer code locally with my changes, tested logs containing Intel integrated graphics along with logs containing Intel Arc GPU's.
Here are some log links to test with:
https://obsproject.com/logs/0nN2UUzOIbYZRfWl
https://obsproject.com/logs/zlZV3S7bSlzk1lVL

Exclude Intel Arc GPU's from the integrated GPU check

---

checks/wayland.py

Add support for https://github.com/obsproject/obs-studio/pull/8212 which replace `Distribution:` on Flatpak.
Keep the Wayland check working.

Add new Flatpak logging support

---

checks/core.py
checks/plugins.py
checks/utils/utils.py
loganalyzer.py

Add a check to let users know what third-party plugins they have installed
Users may need to remove third-party plugins during the process of troubleshooting but often don't know everything they have installed. This will give them a list to reference.
Ran the log analyzer code locally with my changes, tested logs from different OBS versions with various plugin setups. Also tested a log that didn't make it to the plugin loading stage to confirm it could handle this.
Logs to test:
Windows log (no plugins): https://obsproject.com/logs/CC8G3rVJE7ddcf-F
Windows log (plugins): https://obsproject.com/logs/nh5Pp3z8ybcBdBTN
Mac log (no plugins): https://obsproject.com/logs/ufI7JkFu10qM9KXJ
Mac log (plugins): https://obsproject.com/logs/vI4vzLpABQ83F5UI
Linux log (no plugins): …

Add check for third-party plugins

---

checks/windows.py

Report that HAGS is enabled when the registry key isn't set.
HAGS being enabled continues to result in OBS performance issues and if the registry key isn't set, it is probably on so this should be reported by the analyzer.
Ran the log analyzer code locally with my changes, tested logs containing the "On", "Probably On", and "Off" strings.
Logs:
https://obsproject.com/logs/u5zg2liWUO8GIVSd
https://obsproject.com/logs/wGReCZRmeiCWDoKH

Update HAGS detection

---

checks/audio.py
loganalyzer.py

Add a check to see if the audio monitoring device has failed to load.
It is a very common issue in the support channels where a user is unable to hear their monitored audio because the device has failed to load. This added check and solution instructions should hopefully allow users to resolve this on their own without having to seek additional support.
Ran the log analyzer code locally with my changes, tested logs with audio monitor devices failing to make sure it displayed the message when applicable.
https://obsproject.com/logs/P37v0V9MO8QF8Ldk

Add check for failed monitoring device

---

checks/macos.py
checks/utils/windowsversions.py
checks/windows.py
loganalyzer.py

Add checks for ARM64 and emulation detectio
https://github.com/obsproject/obs-studio/pull/5738

Add checks for ARM64 and emulation detection

---

loganalyzer.py

This line was accidentally removed when #113 got merged, this adds it back.
Fixes a missing line from #115 .
Ran the analyzer and confirmed third-party plugins are now showing as expected.

Add missing checkPluginList call

---

checks/graphics.py

This updates the NVIDIA driver website URL to the .com URL instead of .de.
Saw the German site was being used.
Website loads.

Update NVIDIA driver website URL

---

checks/network.py

Fix check for 100 Mbps on Gigabit NIC.
New ethernet adapter log format reported by @notr1ch . Want analyzer checks to work.
Tested changes locally.

Fix check for 100 Mbps on Gigabit NIC

---

checks/core.py
loganalyzer.py

Currently, if you upload an OBS Studio crash log to the analyzer, it will crash. Instead of crashing, let's just check if it's a crash log, and provide an alert that the analyzer does not yet process those logs.
Don't want the analyzer crashing.
Tested locally.

Detect OBS crash log with basic handling

---

checks/windows.py

Updates the HAGS logging detection to include the new string logged on OBS 29.1.2 and later.
This allows the analyzer to properly detect when HAGS is enabled.
Tested with the following log:
https://obsproject.com/logs/sKBCjFqiKmvE8quG

Update HAGS detection for 29.1.2 logging changes

---

checks/utils/windowsversions.py

Fix and update Windows 10/11 22H2 date
1. https://docs.microsoft.com/windows/release-health/windows11-release-information
2. https://learn.microsoft.com/windows/release-health/release-information
3. https://docs.microsoft.com/lifecycle/announcements/windows-10-22h2-end-of-support-update

Fix and update Windows 10/11 22H2 date

---

checks/network.py
loganalyzer.py

Add a check for Lenovo vantage now that it is being logged.
Lenovo Vantage has a Network Boost feature which is on by default and is guaranteed to cause OBS to drop frames while streaming.
Tested with this log from a user with Lenovo Vantage installed:
https://obsproject.com/logs/P0U7doFsxkOqOTLL

Add check for Lenovo Vantage

---

checks/core.py
loganalyzer.py

Look for 'Portable mode: true' in the log and add an info flag if found.
It is useful information for troubleshooting some issues.
Tested with this log from an OBS instance running in portable mode: https://obsproject.com/logs/ritmAH18y1g27iIe

Add check for portable mode

---

checks/core.py
loganalyzer.py

Look for 'Safe Mode Enabled' in the log and add a warning flag if found.
Safe Mode is a new feature which makes troubleshooting issues much easier. It should be made obvious to a user or someone assisting them if they are running OBS with safe mode turned on.
Confirmed that the Safe Mode warning flag is showing when analyzing a log with it enabled: https://obsproject.com/logs/TK9zZeeQZnGdswon

Add check for Safe Mode

---

checks/audio.py

Check for a matching source before trying to append its name.
A users log was causing analyzer to fail.
Confirmed this log no longer fails: https://obsproject.com/logs/8VY6qyf4t2lIq891

audio: Check for source match

---

checks/network.py

Update the Killer Software Suite link and instructions.
The link was updated in the OBS Discord, updating here to match.
The link works.

checks: Update Killer link

---

.github/workflows/main.yml

Update first-party GitHub Actions actions/checkout and actions/setup-python.
Prevent the node16 deprecation warnings on CI.
It hasn't been tested. Hopefully CI will be green.
- Code cleanup (non-breaking change which makes code smaller or more readable)

Update first-party GitHub Actions

---

checks/network.py
checks/utils/utils.py

When scanning the log fro dropped frames, this ignores any reported by the autoconfig wizard's test stream.
Alongside this, it introduces a new util function, searchExclude, that allows searching lines for a term while excluding others. It was added as a separate function because I felt other parts of the analyzer or future additions to it could benefit from it for clarity and simplicity. If that is deemed unnecessary or better done in a separate PR, it can obviously be changed easily.
The autoconfig wizard will always report dropped frames as part of it's normal behaviour, without it being indicative of any actual network issues.
As such reporting those in the analyzer can mistakenly lead users to think they have a network issue when they do not.
Tested by manually feeding lines to the …

network: Ignore autoconfig when checking for dropped frames

---

checks/plugins.py

Include mac-avcapture-legacy as a first-party plugin.
This should not be flagged as a third-party plugin.
It hasn't but it should be fine.

plugins: Add mac-avcapture-legacy to macPlugins list

---

checks/plugins.py

Add these to the list of commonPlugins so they no longer flag as third-party plugins starting on OBS Studio 31.0.0
New version of OBS ships these.
Didn't test but it seems straight forward enough.

plugins: Add obs-nvenc and nv-filters to commonPlugins

---

checks/utils/windowsversions.py

Add detection for Windows 11 24H2.
This released on 10/01/2024, should no longer show as an insider version.
Now properly detects 24H2 using this log https://obsproject.com/logs/s4YlrFOqhbWtCaMi

windowsversions: Add Windows 11 24H2

---

requirements.txt

Update requests to 2.32.0 and aiohttp to 3.10.11
Resolve dependency warnings.
It hasn't.

Update requests to 2.32.0 and aiohttp to 3.10.11

---

loganalyzer.py

Keep a record of messages that have already been added to prevent duplicates.
Saw this log with two "Capture Interference" messages: https://obsproject.com/logs/3uhJYYDLFiwJJiBz
Tested with the above log.
Currently: 
This PR:

loganalyzer: Prevent duplicate messages

---

checks/windows.py

Remove a debug print statement.
Noticed additional print output while testing locally.
It seems like I left this in by accident when committing efa34ab3f92e8894ad7f7c52164f76a417e1583e.
Tested locally on Windows 11.
- Code cleanup (non-breaking change which makes code smaller or more readable)

windows: Remove debug print statement
